//! Integration test: raw log → template parsing → cache/embedding pipeline.
//! Requires models/ files generated by running `scripts/download_model.sh` to work (skips if not found).

use std::path::PathBuf;

use turbolog::{AnomalyDetector, DetectionResult, Embedder, PingPongIndexer, VectorCache};

fn models_dir() -> Option<PathBuf> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models");
    (dir.join("model.onnx").exists() && dir.join("tokenizer.json").exists()).then_some(dir)
}

/// 5 templates × 20 logs = 100 synthetic logs.
fn synthetic_logs() -> Vec<String> {
    let mut logs = Vec::new();
    for i in 0..20 {
        logs.push(format!(
            "connection accepted from 10.0.0.{i} port {}",
            5000 + i
        ));
        logs.push(format!("user u{i} login success from web console"));
        logs.push(format!("disk usage at {} percent on /var", 50 + i));
        logs.push(format!("request to /api/v1/items took {} ms", 10 * i + 3));
        logs.push(format!(
            "worker {i} heartbeat ok at epoch {}",
            1700000000 + i
        ));
    }
    logs
}

#[test]
fn pipeline_cache_hit_rate_and_vector_shape() {
    let Some(dir) = models_dir() else {
        eprintln!("skip: models/ not found — run ./scripts/download_model.sh first");
        return;
    };
    let embedder = Embedder::new(dir.join("model.onnx"), dir.join("tokenizer.json")).unwrap();
    let mut cache = VectorCache::new(embedder);

    let mut first_vector: Option<std::sync::Arc<[f32]>> = None;
    for log in synthetic_logs() {
        let (parsed, vector) = cache.get_or_embed(&log).unwrap();
        assert_eq!(vector.len(), 384, "all-MiniLM-L6-v2 is 384-dimensional");
        let norm = vector.iter().map(|v| v * v).sum::<f32>().sqrt();
        assert!((norm - 1.0).abs() < 1e-3, "L2 normalized norm={norm}");
        assert!(!parsed.template.is_empty());
        first_vector.get_or_insert(vector);
    }

    let total = cache.hits() + cache.misses();
    assert_eq!(total, 100);
    // With 5 templates, misses should be few — as Drain templates evolve in the first few logs,
    // 1~2 misses per template may occur, so we set the hit rate lower bound to 90%.
    assert!(
        cache.hit_rate() >= 0.90,
        "Hit rate {:.1}% (hits={}, misses={})",
        cache.hit_rate() * 100.0,
        cache.hits(),
        cache.misses()
    );
    println!(
        "Cache hit rate: {:.1}% (hits={}, misses={})",
        cache.hit_rate() * 100.0,
        cache.hits(),
        cache.misses()
    );
}

#[test]
fn cache_hit_skips_embedding() {
    let Some(dir) = models_dir() else {
        eprintln!("skip: models/ not found — run ./scripts/download_model.sh first");
        return;
    };
    let embedder = Embedder::new(dir.join("model.onnx"), dir.join("tokenizer.json")).unwrap();
    let mut cache = VectorCache::new(embedder);

    let (a, va) = cache.get_or_embed("Node 2 is online").unwrap();
    assert_eq!(cache.misses(), 1);
    let (b, vb) = cache.get_or_embed("Node 7 is online").unwrap();
    assert_eq!(
        a.template_id, b.template_id,
        "Logs with different variables only should map to the same template"
    );
    assert_eq!(cache.hits(), 1, "Second ingestion is a cache hit");
    assert_eq!(cache.misses(), 1, "No additional embedding call");
    assert!(std::sync::Arc::ptr_eq(&va, &vb), "Shared same cache entry");
}

/// E2E: log text → embedding → indexing → 2-tier anomaly detection.
#[test]
fn end_to_end_anomaly_detection() {
    let Some(dir) = models_dir() else {
        eprintln!("skip: models/ not found — run ./scripts/download_model.sh first");
        return;
    };
    let embedder = Embedder::new(dir.join("model.onnx"), dir.join("tokenizer.json")).unwrap();
    let mut cache = VectorCache::new(embedder);

    // 1) Ingest normal logs → collect vectors + ping-pong indexing
    let indexer = PingPongIndexer::new(384, 4).unwrap();
    let mut normal_flat: Vec<f32> = Vec::new();
    let mut next_id = 0u64;
    for log in synthetic_logs() {
        let (parsed, vector) = cache.get_or_embed(&log).unwrap();
        next_id += 1;
        indexer.ingest(next_id, &vector).unwrap();
        // Add to calibration set only once per template (miss time = new template)
        let _ = parsed;
        if cache.misses() as usize * 384 > normal_flat.len() {
            normal_flat.extend_from_slice(&vector);
        }
    }
    indexer.swap_and_flush(None).unwrap();
    let snapshot = indexer.get_search_index();

    // 2) Freeze centroids with 5 normal templates (k=5)
    let detector = AnomalyDetector::fit(&normal_flat, 384, 5, 0.5);

    // 3) Re-ingest normal logs → bypass Tier 1 immediately
    let (_p, v) = cache
        .get_or_embed("disk usage at 77 percent on /var")
        .unwrap();
    assert!(
        matches!(detector.detect(&v, &snapshot), DetectionResult::Normal),
        "Existing template logs are Normal"
    );

    // 4) Never-before-seen fatal log → Anomaly + similar incident context
    let (_p, v) = cache
        .get_or_embed("FATAL kernel panic at address 0xdeadbeef, halting node")
        .unwrap();
    match detector.detect(&v, &snapshot) {
        DetectionResult::Anomaly {
            score,
            nearest_incidents,
        } => {
            assert!(score > 0.5, "score={score}");
            assert!(!nearest_incidents.is_empty(), "Secured similar context in recent window");
            println!("Anomaly detected: score={score:.3}, nearest incidents={nearest_incidents:?}");
        }
        DetectionResult::Normal => panic!("Fatal log classified as Normal"),
    }
}
